#!/bin/bash
# =============================================================================
# carbonite-restore.sh — Restore sandbox state from Carbonite backup
# =============================================================================
# Run this on the HOST after a sandbox rebuild to restore backed-up state.
#
# PRECONDITION: Restore assumes a clean/disposable sandbox. The target
# /sandbox directory should be in its default post-creation state. This
# script uploads over it without clearing first — in a fresh sandbox
# this is deterministic. Do NOT run against a sandbox with meaningful
# uncommitted work.
#
# What it does:
#   1. Clones the configured carbonite repo to a temp directory on the host via gh
#   2. Packages the restore tree as a tarball (preserves symlinks/layout)
#   3. Packages trusted current restore helpers from this clawrbonite checkout
#   4. Uploads both tarballs into a writable sandbox tmp directory via openshell sandbox upload
#   5. Cleans up temp directory
#
# After upload, connect to the sandbox and run:
#   mkdir -p ~/.openclaw
#   tar -xf /tmp/carbonite-restore-upload/carbonite-restore.tar -C ~/.openclaw
#   tar -xf /tmp/carbonite-restore-upload/carbonite-restore-helpers.tar -C ~/.openclaw
#   bash ~/.openclaw/carbonite/carbonite-init.sh --continue --no-push
#
# Prerequisites:
#   - Sandbox must be running (openshell sandbox list shows it Ready)
#   - GitHub CLI (`gh`) installed and already authenticated on the host
#   - openshell CLI installed on host
#
# Usage:
#   bash carbonite-restore.sh [sandbox-name]
#   CARBONITE_REPO_URL=https://github.com/snarkipus/carbonite-scratch.git \
#     bash carbonite-restore.sh my-assistant
# =============================================================================

set -euo pipefail

SANDBOX_NAME="${1:-my-assistant}"
DEFAULT_REPO_URL="https://github.com/snarkipus/carbonite.git"
REPO_URL="${CARBONITE_REPO_URL:-$DEFAULT_REPO_URL}"
REPO_SLUG="${REPO_URL#https://github.com/}"
REPO_SLUG="${REPO_SLUG%.git}"
TMPDIR="/tmp/carbonite-restore-$$"
UPLOAD_DIR="${TMPDIR}/upload"
ARCHIVE_NAME="carbonite-restore.tar"
ARCHIVE_PATH="${UPLOAD_DIR}/${ARCHIVE_NAME}"
HELPERS_ARCHIVE_NAME="carbonite-restore-helpers.tar"
HELPERS_ARCHIVE_PATH="${UPLOAD_DIR}/${HELPERS_ARCHIVE_NAME}"
HISTORY_ARCHIVE_NAME="carbonite-history.tar"
HISTORY_ARCHIVE_PATH="${UPLOAD_DIR}/${HISTORY_ARCHIVE_NAME}"
SANDBOX_UPLOAD_DIR="/tmp/carbonite-restore-upload"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELPER_STAGE_DIR="${TMPDIR}/helpers"

materialized_github_token() {
  local token="${GH_PAT:-${GITHUB_TOKEN:-}}"
  if [ -n "$token" ] && [[ "$token" != openshell:resolve:env:* ]]; then
    printf '%s\n' "$token"
  fi
}

write_carbonite_env_helper() {
  local target="$1"
  local token="$2"

  umask 077
  {
    echo "# Carbonite local env helper — generated by carbonite-restore.sh."
    echo "# This file is excluded from Carbonite backups and contains sandbox-local auth."
    printf 'export GITHUB_TOKEN=%q\n' "$token"
    cat << 'ENV_HELPER'
export SEARXNG_URL="http://host.openshell.internal:8888"
case ":$PATH:" in
  *":$HOME/.openclaw/carbonite/bin:"*) ;;
  *) export PATH="$HOME/.openclaw/carbonite/bin:$PATH" ;;
esac
ENV_HELPER
  } > "$target"
}

echo "==> Carbonite Restore"
echo "    Sandbox: ${SANDBOX_NAME}"
echo "    Repo:    ${REPO_URL}"
echo ""

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: gh is required on the host for Carbonite restore."
  exit 1
fi

if [ -z "$REPO_SLUG" ] || [ "$REPO_SLUG" = "$REPO_URL" ]; then
  echo "ERROR: CARBONITE_REPO_URL must be a GitHub repo URL (got: ${REPO_URL})."
  exit 1
fi

echo "==> Checking host GitHub CLI auth..."
if ! gh auth status >/dev/null 2>&1; then
  echo "ERROR: gh is not authenticated for GitHub access on the host."
  exit 1
fi

# ── Verify sandbox is running ───────────────────────────────────────────────
echo "==> Checking sandbox status..."
if ! openshell sandbox list 2>/dev/null | grep -q "${SANDBOX_NAME}"; then
  echo "ERROR: Sandbox '${SANDBOX_NAME}' not found or not running."
  echo "       Run 'openshell sandbox list' to check."
  exit 1
fi

# ── Clone repo ──────────────────────────────────────────────────────────────
echo "==> Cloning carbonite to ${TMPDIR}..."
mkdir -p "${TMPDIR}" "${UPLOAD_DIR}"
gh repo clone "$REPO_SLUG" "${TMPDIR}/carbonite" -- --depth 1
gh repo clone "$REPO_SLUG" "${TMPDIR}/carbonite-history.git" -- --bare

# Remove .git directory — Carbonite's own repo state will be re-initialized
rm -rf "${TMPDIR}/carbonite/.git"

# ── Package restore archive ────────────────────────────────────────────────
echo "==> Packaging restore archive..."
tar -cf "${ARCHIVE_PATH}" -C "${TMPDIR}/carbonite" .
tar -cf "${HISTORY_ARCHIVE_PATH}" -C "${TMPDIR}" carbonite-history.git

# ── Package trusted current helper overlay ─────────────────────────────────
echo "==> Packaging trusted current helper overlay..."
mkdir -p "${HELPER_STAGE_DIR}/carbonite/bin"
cp -f "${SCRIPT_DIR}/carbonite-init.sh" "${HELPER_STAGE_DIR}/carbonite/carbonite-init.sh"
cp -f "${SCRIPT_DIR}/carbonite-cron-setup.sh" "${HELPER_STAGE_DIR}/carbonite/carbonite-cron-setup.sh"
cp -f "${SCRIPT_DIR}/carbonite-backup.sh" "${HELPER_STAGE_DIR}/carbonite/bin/carbonite-backup"
cp -f "${SCRIPT_DIR}/carbonite-bundle.sh" "${HELPER_STAGE_DIR}/carbonite/bin/carbonite-bundle"
cp -f "${SCRIPT_DIR}/env-setup.sh" "${HELPER_STAGE_DIR}/carbonite/bin/env-setup"
cp -f "${SCRIPT_DIR}/websearch.sh" "${HELPER_STAGE_DIR}/carbonite/bin/websearch"
if TOKEN="$(materialized_github_token)"; then
  echo "    Including sandbox-local Carbonite env helper from host-provided GitHub token."
  write_carbonite_env_helper "${HELPER_STAGE_DIR}/carbonite/env.sh" "$TOKEN"
  chmod 600 "${HELPER_STAGE_DIR}/carbonite/env.sh"
fi
tar -cf "${HELPERS_ARCHIVE_PATH}" -C "${HELPER_STAGE_DIR}" .

# ── Upload to sandbox ──────────────────────────────────────────────────────
echo "==> Uploading to sandbox '${SANDBOX_NAME}'..."
echo "    Source tree: ${TMPDIR}/carbonite/"
echo "    Archive:     ${ARCHIVE_PATH}"
echo "    Result:      ${ARCHIVE_NAME}, ${HELPERS_ARCHIVE_NAME}, and ${HISTORY_ARCHIVE_NAME} land at ${SANDBOX_UPLOAD_DIR}/"
echo ""

if ! openshell sandbox upload "${SANDBOX_NAME}" "${UPLOAD_DIR}" "${SANDBOX_UPLOAD_DIR}"; then
  echo "ERROR: Restore archive upload failed. Sandbox contents may be partial."
  exit 1
fi

# ── Cleanup ─────────────────────────────────────────────────────────────────
echo ""
echo "==> Cleaning up temp directory..."
rm -rf "${TMPDIR}"

echo ""
echo "==> Restore complete!"
echo ""
echo "==> Next steps (inside sandbox):"
echo "    1. Connect:  nemoclaw ${SANDBOX_NAME} connect"
echo "    2. Extract:  mkdir -p ~/.openclaw && tar -xf ${SANDBOX_UPLOAD_DIR}/${ARCHIVE_NAME} -C ~/.openclaw/"
echo "    3. Refresh:  tar -xf ${SANDBOX_UPLOAD_DIR}/${HELPERS_ARCHIVE_NAME} -C ~/.openclaw/"
echo "    4. Verify:   ls -la ~/.openclaw/carbonite ~/.openclaw/carbonite/bin"
echo "    5. Init:     bash ~/.openclaw/carbonite/carbonite-init.sh --continue --no-push"
echo ""
echo "    The trusted helper overlay will:"
echo "      - Replace stale archived restore-control helpers with the current clawrbonite versions"
echo "      - Ensure restore control follows the current runtime root contract"
echo ""
echo "    The validation init will:"
echo "      - Preserve Carbonite git history"
echo "      - Prefer uploaded host-cloned git history before sandbox GitHub clone"
echo "      - Thaw .carbonite.bundle files back to .git dirs"
echo "      - Validate restored nested repos"
echo "      - Install backup & bundle scripts to ~/.openclaw/carbonite/bin/"
echo "      - Install trusted helper CLIs such as websearch to ~/.openclaw/carbonite/bin/"
echo "      - Skip restore commit/push until you validate the restored state"
echo ""
echo "    6. Cron:     bash ~/.openclaw/carbonite/carbonite-cron-setup.sh"
echo "    7. Env:      bash ~/.openclaw/carbonite/bin/env-setup    # optional helper template"
echo "    8. Test:     ~/.openclaw/carbonite/bin/carbonite-backup 'post-restore verification'"
echo ""
