#!/bin/bash
# =============================================================================
# carbonite-provision-auth.sh — Install sandbox-local Carbonite auth helper
# =============================================================================
# Run this on the HOST when a restored sandbox needs a materialized token for
# local Carbonite cron/backup git push operations.
#
# Usage:
#   GH_PAT=ghp_... bash carbonite-provision-auth.sh [sandbox-name]
# =============================================================================

set -euo pipefail

SANDBOX_NAME="${1:-my-assistant}"
TOKEN="${GH_PAT:-${GITHUB_TOKEN:-}}"
TMPDIR="/tmp/carbonite-provision-auth-$$"
ARCHIVE_PATH="${TMPDIR}/carbonite-auth-helper.tar"

cleanup() {
  rm -rf "$TMPDIR"
}
trap cleanup EXIT

if [ -z "$TOKEN" ] || [[ "$TOKEN" == openshell:resolve:env:* ]]; then
  echo "ERROR: Set GH_PAT or a materialized GITHUB_TOKEN before running this helper."
  exit 1
fi

mkdir -p "${TMPDIR}/carbonite"
umask 077
{
  echo "# Carbonite local env helper — generated by carbonite-provision-auth.sh."
  echo "# This file is excluded from Carbonite backups and contains sandbox-local auth."
  printf 'export GITHUB_TOKEN=%q\n' "$TOKEN"
  cat << 'ENV_HELPER'
export SEARXNG_URL="http://host.openshell.internal:8888"
case ":$PATH:" in
  *":$HOME/.openclaw/carbonite/bin:"*) ;;
  *) export PATH="$HOME/.openclaw/carbonite/bin:$PATH" ;;
esac
ENV_HELPER
} > "${TMPDIR}/carbonite/env.sh"
chmod 600 "${TMPDIR}/carbonite/env.sh"

tar -cf "$ARCHIVE_PATH" -C "$TMPDIR" carbonite/env.sh

echo "==> Provisioning Carbonite auth helper"
echo "    Sandbox: ${SANDBOX_NAME}"
echo "    Target:  /sandbox/.openclaw/carbonite/env.sh"
echo ""

openshell sandbox upload "$SANDBOX_NAME" "$ARCHIVE_PATH" /tmp/carbonite-auth-helper.tar
openshell sandbox exec -n "$SANDBOX_NAME" -- tar -xf /tmp/carbonite-auth-helper.tar -C /sandbox/.openclaw
openshell sandbox exec -n "$SANDBOX_NAME" -- sh -lc 'chmod 600 /sandbox/.openclaw/carbonite/env.sh && rm -f /tmp/carbonite-auth-helper.tar'

echo "==> Carbonite auth helper provisioned."
